[theme]
base = "dark"
backgroundColor = "#070314"
secondaryBackgroundColor = "#0c0620"
primaryColor = "#a855f7"
textColor = "#f1f5f9"

[browser]
gatherUsageStats = false

[server]
headless = true
port = 8501
